
import { GoogleGenAI, Modality, Part } from "@google/genai";

// Helper function to convert a File object to a base64 string and return a Part
const fileToGenerativePart = async (file: File): Promise<Part> => {
  const base64EncodedDataPromise = new Promise<string>((resolve) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve((reader.result as string).split(',')[1]);
    reader.readAsDataURL(file);
  });
  return {
    inlineData: {
      data: await base64EncodedDataPromise,
      mimeType: file.type,
    },
  };
};

// Helper function to fetch an image from a URL, convert to base64, and return a Part
const imageUrlToGenerativePart = async (url: string): Promise<Part> => {
    // Using a proxy to bypass potential CORS issues with direct fetching from certain image hosts
    const proxyUrl = `https://cors-anywhere.herokuapp.com/${url}`;
    try {
        const response = await fetch(proxyUrl);
        if (!response.ok) {
            throw new Error(`Failed to fetch image from URL: ${url}. Status: ${response.statusText}`);
        }
        const blob = await response.blob();
        const base64EncodedDataPromise = new Promise<string>((resolve, reject) => {
            const reader = new FileReader();
            reader.onloadend = () => resolve((reader.result as string).split(',')[1]);
            reader.onerror = reject;
            reader.readAsDataURL(blob);
        });
        return {
            inlineData: {
                data: await base64EncodedDataPromise,
                mimeType: blob.type,
            },
        };
    } catch (error) {
       console.warn(`CORS proxy failed. Trying direct fetch for ${url}. This may fail in some browsers.`);
        const directResponse = await fetch(url);
        if (!directResponse.ok) {
            throw new Error(`Direct fetch also failed for image URL: ${url}. Status: ${directResponse.statusText}`);
        }
        const blob = await directResponse.blob();
        const base64EncodedDataPromise = new Promise<string>((resolve, reject) => {
            const reader = new FileReader();
            reader.onloadend = () => resolve((reader.result as string).split(',')[1]);
            reader.onerror = reject;
            reader.readAsDataURL(blob);
        });
        return {
            inlineData: {
                data: await base64EncodedDataPromise,
                mimeType: blob.type,
            },
        };
    }
};


export const generateMockup = async (logoFile: File, productUrl: string, userPrompt: string): Promise<string> => {
    if (!process.env.API_KEY) {
        throw new Error("API_KEY environment variable not set");
    }
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

    const logoPart = await fileToGenerativePart(logoFile);
    const productPart = await imageUrlToGenerativePart(productUrl);

    const promptText = `
        Your task is to create a photorealistic product mockup.
        1.  You will be given a product image and a logo image.
        2.  Place the logo onto the product image.
        3.  The user has provided the following instruction for placement and style: "${userPrompt}".
        4.  If the user's instruction is vague, place the logo in the most natural and common position for that product (e.g., center chest for a t-shirt, front for a mug).
        5.  The final image should look like a real photograph. The logo should blend naturally with the product's texture, lighting, and contours. Do not just paste a flat logo on top.
        6.  The output must be ONLY the final image. Do not add any text, borders, or other elements.
    `;

    const contents = {
        parts: [
          { text: promptText },
          productPart,
          logoPart
        ],
    };

    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: contents,
        config: {
            responseModalities: [Modality.IMAGE],
        },
    });

    for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
            const base64ImageBytes: string = part.inlineData.data;
            const mimeType = part.inlineData.mimeType;
            return `data:${mimeType};base64,${base64ImageBytes}`;
        }
    }
    
    throw new Error('No image was generated by the API.');
};
